server:
  port: 8888

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    instance-id: configApp
    prefer-ip-address: true

spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config/ # 搜索src/main/resource 下的config文件夹下的文件
  profiles:
    active: native  # 配置使用本地储存
