eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 80

spring:
  application:
    name: innerzuul-proj
zuul:
  routes:
    api-sys:
      path: /api-sys/**
      serviceId: sys-proj

    api-base:
      path: /api-base/**
      serviceId: base-proj

    api-ai:
      path: /api-ai/**
      serviceId: ai_proj

    api-flow:
      path: /api-flow/**
      serviceId: flow_proj

    api-job:
      path: /api-job/**
      serviceId: job_proj

    api-link:
      path: /api-link/**
      serviceId: link-proj

    api-log:
      path: /api-log/**
      serviceId: log-proj

    api-report:
      path: /api-report/**
      serviceId: report-proj
