eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    instance-id: bountyApp
    prefer-ip-address: true

server:
  port: 8011
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: bounty-proj
  datasource:
    name: bounty_db
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.1.9.160:1521/pm
    username: zjk
    password: zjk2018
    #配置初始化大小/最小/最大
    initial-size: 1
    min-idle: 1
    max-active: 20
  rabbitmq:
    host: 106.0.0.51
    port: 5672
    username: guest
    password: gtuest
    template:
      routing-key: 123456
      exchange: f3
      default-receive-queue: q1




mybatis:
  mapper-locations: classpath:config/mapper/*.xml
  type-aliases-package: com.bw.fit

#pagehelper
pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check
