eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    instance-id: apiApp
    prefer-ip-address: true

server:
  port: 80
  max-http-header-size: 10485760
  tomcat:
    uri-encoding: utf-8

spring:
  application:
    name: api-proj

zuul:
  SendErrorFilter:
    post:
      disable: true
  routes:
    api-sys:
      path: /api-sys/**
      serviceId: sys-proj
      url: http://localhost:8001/sys/

    api-base:
      path: /api-base/**
      serviceId: base-proj
      url: http://localhost:8002/base/

    api-api:
      path: /api-api/**
      serviceId: api-proj
      url: http://localhost:80/

    api-ai:
      path: /api-ai/**
      serviceId: ai_proj

    api-flow:
      path: /api-flow/**
      serviceId: flow2_proj
      url: http://localhost:8004/

    api-job:
      path: /api-job/**
      serviceId: job_proj

    api-link:
      path: /api-link/**
      serviceId: link-proj

    api-log:
      path: /api-log/**
      serviceId: log-proj

    api-report:
      path: /api-report/**
      serviceId: report-proj

    api-cache:
      path: /api-cache/**
      serviceId: cache-proj
      url: http://localhost:9001/cache/

    api-bounty:
      path: /api-bounty/**
      serviceId: bounty-proj
      url: http://localhost:8011/bounty/


#系统统一字符串的分隔符
cutFlag: CUTFLAG