server:
  port: 8002
  tomcat:
    uri-encoding: UTF-8


spring:
  application:
    name: common-proj
  datasource:
    name: common_db
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: ENC(uVkoTjga4RvFzNw+koWGOxg9k9Z3CUBlf9KjFKiYAol5mcPm32nit6I5Te9gnlYr)
    username: fit4
    password: fit4123456
    #配置初始化大小/最小/最大
    initial-size: 10
    min-idle: 5
    max-active: 200
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，此处是filter修改的地方
    filters:
      commons-log.connection-logger-name: stat,wall,log4j,logback
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true


#jasypt加密的密匙
jasypt:
  encryptor:
    password: EbfYkitulv73I2p0mXI50JMXoaxNMG


mybatis:
  mapper-locations: classpath:config/mapper/*Mapper.xml
  type-aliases-package: com.bw.fit
  configuration:
    map-underscore-to-camel-case: true


#pagehelper
pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check


#系统统一字符串的分隔符
cutFlag: CUTFLAG