server:
  port: 8004
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: flow2-proj
  datasource:
    name: flow2_db
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.1.9.160:1521/pm
    username: fit4
    password: fit4123456
    #配置初始化大小/最小/最大
    initial-size: 10
    min-idle: 5
    max-active: 20


  activiti:
    history-level: full
    database-schema: ACT
    check-process-definitions: true
    process-definition-location-prefix: classpath:processes/
    database-schema-update: none
#    process-definition-location-suffixes:
#      - **.bpmn
#      - **.bpmn20.xml

mybatis:
  mapper-locations: classpath:config/mapper/*Mapper.xml
  type-aliases-package: com.bw.fit
  configuration:
    map-underscore-to-camel-case: true



#系统统一字符串的分隔符
cutFlag: CUTFLAG


#工作流系统支持的办结方式
flow:
  handleways:
    listmap:
      - code: pass
        name: 通过
      - code: reject
        name: 驳回
      - code: proxy
        name: 转办

#工作流系统支持表单格式类型
form:
  tabtypes:
    listmap:
      - code: kvtab
        name: 键值表单
      - code: listtab
        name: 列数据表单
      - code: atttab
        name: 附件表单