eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    instance-id: apiApp
    prefer-ip-address: true
server:
  port: 80

spring:
  application:
    name: api-proj
zuul:
  routes:
    api-sys:
      path: /api-sys/**
      serviceId: sys-proj
      url: http://localhost:8001/sys/

    api-base:
      path: /api-base/**
      serviceId: base-proj
      url: http://localhost:8002/base/

    api-ai:
      path: /api-ai/**
      serviceId: ai_proj

    api-flow:
      path: /api-flow/**
      serviceId: flow_proj

    api-job:
      path: /api-job/**
      serviceId: job_proj

    api-link:
      path: /api-link/**
      serviceId: link-proj

    api-log:
      path: /api-log/**
      serviceId: log-proj

    api-report:
      path: /api-report/**
      serviceId: report-proj

    api-cache:
      path: /api-cache/**
      serviceId: cache-proj
      url: http://localhost:9001/cache/