eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    instance-id: aiApp
    prefer-ip-address: true
server:
  port: 8003
spring:
  application:
    name: ai-proj