eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    instance-id: linkApp
    prefer-ip-address: true
server:
  port: 8006
spring:
  application:
    name: link-proj