eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 8001
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /sys

spring:
  application:
    name: sys-proj
  datasource:
    name: sys_db
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.1.9.160:1521/pm
    username: fit3
    password: fit123456
    #配置初始化大小/最小/最大
    initial-size: 1
    min-idle: 1
    max-active: 20

mybatis:
  mapper-locations: classpath:config/mapper/*.xml
  type-aliases-package: com.bw.fit

#pagehelper
pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check


