eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    instance-id: sysApp
    prefer-ip-address: true

server:
  port: 8001
  tomcat:
    uri-encoding: UTF-8


spring:
  application:
    name: sys-proj
  datasource:
    name: sys_db
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.1.9.160:1521/pm
    username: zjk
    password: zjk2018
    #配置初始化大小/最小/最大
    initial-size: 10
    min-idle: 5
    max-active: 20



mybatis:
  mapper-locations: classpath:config/mapper/*Mapper.xml
  type-aliases-package: com.bw.fit
  configuration:
    map-underscore-to-camel-case: true

#pagehelper
pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

#租户对应数据源
custom:
    datasource:
      names: tenantcm001,tenantcm002
      tenantcm001:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@10.1.9.160:1521/pm
        username: fit4
        password: fit4123456
      tenantcm002:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@10.1.9.160:1521/pm
        username: pm
        password: pm123456