eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    instance-id: jobApp
    prefer-ip-address: true

server:
  port: 8005
spring:
  application:
    name: job-proj