eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    instance-id: flowApp
    prefer-ip-address: true
server:
  port: 8004

spring:
  application:
    name: flow-proj
  datasource:
    name: flow_db
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.1.9.160:1521/pm
    username: zjk
    password: zjk2018
    #配置初始化大小/最小/最大
    initial-size: 1
    min-idle: 1
    max-active: 20

mybatis:
  mapper-locations: classpath:config/mapper/*Mapper.xml
  type-aliases-package: com.bw.fit
  configuration:
    map-underscore-to-camel-case: true

  activiti:
    history-level: full
    database-schema: true
    check-process-definitions: false
    process-definition-location-prefix: classpath:/processes/
    process-definition-location-suffixes:
      - **.bpmn
      - **.bpmn20.xml